### ISSUE TITLE
Some Classification Operators haven't "Param Grid" parameters 

### ISSUE THREAD

**Issue by ojvictor** [eubr-bigsea/tahiti#34]
![execution_empty_field_pc](https://user-images.githubusercontent.com/6419508/30545029-d0bea596-9c5e-11e7-81ac-363fd1f11298.png)
![execution_empty_field_dt](https://user-images.githubusercontent.com/6419508/30545011-c35f56fc-9c5e-11e7-8dc0-e6105a3879cb.png)
![execution_empty_field_gbt](https://user-images.githubusercontent.com/6419508/30545023-cc6bc1fe-9c5e-11e7-8caf-699fa4b975be.png)

**Comment by waltersf** [comment]
Fixed
