### ISSUE TITLE
Some Operators haven't execution parameters 

### ISSUE THREAD

**Issue by ojvictor** [eubr-bigsea/tahiti#35]
![execution_empty_field_int](https://user-images.githubusercontent.com/6419508/30546011-c992d01e-9c61-11e7-8073-1a3ef8ddd6b6.png)
![execution_empty_field_ra](https://user-images.githubusercontent.com/6419508/30546064-ed4107f6-9c61-11e7-9489-97fd0a1d5ea9.png)
![execution_empty_field_rv](https://user-images.githubusercontent.com/6419508/30546077-f367497e-9c61-11e7-9808-38e42fec64c8.png)
![execution_empty_field_svm](https://user-images.githubusercontent.com/6419508/30546206-55a6ca92-9c62-11e7-9b45-7bf837b57948.png)
![execution_empty_field_sm](https://user-images.githubusercontent.com/6419508/30546089-fe0f269e-9c61-11e7-9b45-925d846a4845.png)
![execution_empty_field_so](https://user-images.githubusercontent.com/6419508/30546093-00355b78-9c62-11e7-9c8d-46f8ce1a94a8.png)

**Comment by waltersf** [comment]
FIXED
